### ISSUE TITLE
Better package structure

### ISSUE THREAD

**Issue by pykong** [juancarlospaco/peewee-extra-fields#10]
Right now this package consists mainly of one big and several smaller files.
To enhance maintainability and make it easier for other to contribute we may refactor the package into several smaller files.

Each file should be only concerned with fields of a particular topic.
Like:
- `DateTime`
- `Money`
- `Internet`

A file called `misc.py` could hold all fields with miscellaneous purpose or which can not be brought under a specific topic.

Ideally the files start with defining BaseClasses at the top from which SubClasses are inherited below.
Like `MoneyField(abstract.class, decimals=2)` 
*pseudo-code:*
- Fiat(MoneyField)
- Crypto(MoneyField, decimals=8)

**Comment by ghost** [comment]
- Peewee is a +6000 Lines single File.
- We are near +1000 Lines File.
- I already started to do so, I split out all the RegEx based, Country based and Legacy fields into its own file.

**Comment by pykong** [comment]
I was not raising an argument against large single file python programs.
I such structure can have disadvantages.

In the case of this package, I however feel it makes sense to restructure.
