### ISSUE TITLE
Replace headline

### ISSUE THREAD

**Issue by pykong** [juancarlospaco/peewee-extra-fields#12]
This is a mess:
![image](https://user-images.githubusercontent.com/20211140/38445645-aae6cb4e-39f4-11e8-8614-741569cdd9c9.png)

A comprehensive list of all fields can not and should not be given in that place.
README / docs are where that belongs. 

I believe it would be better to just describe this project in a single main sentence.

**Comment by juancarlospaco** [comment]
Yes, that was a quick copypaste.
I changed it for `Extra Fields for Peewee 3 on Python 3.`

**Comment by pykong** [comment]
Looks awesome now.
