### ISSUE TITLE
Add EnumField

### ISSUE THREAD

**Issue by pykong** [juancarlospaco/peewee-extra-fields#6]
I believe adding adding a custom field for the new python `enum` type would be great.
It is especially useful for defining choices, as `enums` enforce value but also provide a string representation.

Some discussion and a code example is provided here:
See: https://github.com/coleifer/peewee/issues/630

From the link above:

```py
class enum_field(CharField):
    """
    This class enable a Enum like field for Peewee
    """
    def __init__(self, choices, *args, **kwargs):
        self.choices = choices
        super(CharField, self).__init__(*args, **kwargs)

    def db_value(self, value):
        return value.name

    def python_value(self, value):
        return self.choices(value)

class my_table(Model):
    class StatusChoices(Enum):
        WAITING = 1
        READY_TO_SEND = 2
        UPLOADING = 3
        OCR = 4
        DONE = 5

    status = enum_like_field(null=False, choices=StatusChoices)
```

**Comment by pykong** [comment]
Another example is here:
https://gist.github.com/b1naryth1ef/607e92dc8c1748a06b5d

**Comment by ghost** [comment]
I agree 100%, can you please send a Pull Request?, with at least 1 passing Unittest, we will merge it!.

Name should be `EnumField`.
