### ISSUE TITLE
Does not work with peewee_migrate

### ISSUE THREAD

**Issue by pykong** [juancarlospaco/peewee-extra-fields#9]
@Klen @juancarlospaco 
I can not simply include fields from `peewee_extra_fields` into my model and migrate.
The reason is that `peewee_migrate` will try to import the additional fields from `peewee` instead.
This requires us to edit the migration file to make it work.
(I am not sure which library is the culprit here.)

Likely there is a simple fix or even a documentation entry for this case.

We should fix this issue as it largely hampers usability of this package.

**Comment by ghost** [comment]
`peewee_migrate` should import our `__all__` https://github.com/juancarlospaco/peewee-extra-fields/blob/master/peewee_extra_fields/__init__.py#L52
and use it to change the imports :grey_question: 

See https://github.com/klen/peewee_migrate/issues/17#issue-164292631

[Does it supports new Peewee 3.x ?](http://docs.peewee-orm.com/en/latest/peewee/changes.html#changes)

:thinking:

**Comment by pykong** [comment]
The compatibility with PeeWee 3.0 is a main issue indeed.
Peewee_migrate does not support 3.0 so far, AFAIK.

I wonder whether you ever experienced the same problem with migrations?

**Comment by ghost** [comment]
Then compatibility with PeeWee 3.0 is a **Blocker**. We cant solve this issue from here.

**Comment by ghost** [comment]
[Theres a new Pull Request on Peewee_Migrate for Peewee 3.0 Compatibility.](https://github.com/klen/peewee_migrate/pull/74#issue-177270736)

**Comment by pykong** [comment]
That are good news! You made my day!
Cuz. I am stuck right now with peewee 2.20.2 for the lack of migration support for peewee 3.
If peewee 3 solves this issue as well, all the better!

I'll suggest we close this issue for now, as it does not appear to be a problem situated in `peewee_extra_fields` itself.

**Comment by juancarlospaco** [comment]
I agree :grey_exclamation:

**Comment by juancarlospaco** [comment]
@pykong https://github.com/keredson/peewee-db-evolve#peewee-db-evolve
